from dataclasses import dataclass

from Utils.reader import Reader
from Utils.writer import Writer
from conf import settings



@dataclass
class BaseController:

    source_code_file_name: str = ''
    source_code_string: str = ''

    def __post_init__(self):
        try:
            if self.source_code_string == '':
                self.source_code_path = settings.get_path(self.source_code_file_name)
                self.reader = Reader(self.source_code_path)
                self.source_code_string = self.reader.read_in_string()
        except FileNotFoundError as file_not_found:
            self.source_code_string = ''
            print(file_not_found.strerror)

    def get_return_value(self) -> str:
        """ Returns the return value of the function """

    def write_ast_to_file(self):
        """ Generates file for ast """

    def get_ast(self):
        """ Returns the generated ast tree """

    def write_ast(self):
        """ Prints the generated ast tree """

    def generate_comment_from_function_name(self):
        """ Generate comment using ast """

    def comment_source_code(self):
        """ Returns the commented source code generated by LazyDoc """

    def comment_functions(self, ast_body):
        """ Comments functions method """
